name: MSBuild

on:
  pull_request:
  push:
    branches:
      - master
      - develop
    paths:
      - '*/**'
      - '!./*'
      - './*.sln'
      - '!.github/**'

jobs:
  build:
    name: MSBuild
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore nuget packages
      run: nuget restore TGMT-CBTC-EX.sln

    - name: MSBuild
      run: msbuild TGMT-CBTC-EX.sln /m /p:configuration="Release" /p:platform="Any CPU" /p:OutputPath="./out/"
      shell: cmd

    - name: Collect artifact
      run: |
        ls -alR
        mkdir plugins/
        mkdir plugins/TGMT-CBTC-EX/
        find . -type f -path '*/out/TGMT-CBTC-EX.dll' | xargs mv -t --force ./plugins/TGMT-CBTC-EX/
        mkdir plugins/TGMT-CBTC-EX_WCU/
        find . -type f -path '*/out/TGMT-CBTC-EX_WCU.dll' | xargs mv -t --force ./plugins/TGMT-CBTC-EX_WCU/
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: plugins
        path: ./plugins/
